INSERT INTO tblRoom VALUES (1,'1강의실',30);
INSERT INTO tblRoom VALUES (2,'2강의실',30);
INSERT INTO tblRoom VALUES (3,'3강의실',30);
INSERT INTO tblRoom VALUES (4,'4강의실',26);
INSERT INTO tblRoom VALUES (5,'5강의실',26);
INSERT INTO tblRoom VALUES (6,'6강의실',26);